apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: index
        image: charleskwakye/index
        ports:
        - containerPort: 80
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: api
        image: charleskwakye/api
        ports:
        - containerPort: 5432
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: database
        image: charleskwakye/database
        ports:
        - containerPort: 8000
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: dbadmin
        image: charleskwakye/dbadmin
        ports:
        - containerPort: 80