apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: LoadBalancer
  selector:
    app: my-app
  ports:
    - name: index
      protocol: TCP
      port: 8081
      targetPort: 80
    - name: api
      protocol: TCP
      port: 5432
      targetPort: 5432
    - name: database
      protocol: TCP
      port: 8000
      targetPort: 8000
    - name: dbadmin
      protocol: TCP
      port: 8082
      targetPort: 80
